### PR TITLE
Fix issue where 3ds modal may not get cleaned up during teardown

### LINKED ISSUE #463: Calling braintreeInstance.teardown() while 3D-secure modal is open doesn't remove modal's html completely
### General information

* SDK/Library version: 1.14.1
* Environment: Sandbox
* Browser and OS: Chrome 70.0.3538.77 (64-bit) on Linux 4.18 

### Issue description

Calling `braintreeInstance.teardown()` while 3D-secure modal is open doesn't remove modal's html completely.

### Steps to reproduce
- Create braintree instance:
```
const braintreeInstance = await dropin.create({
        authorization,
        container,
        card: {
          overrides: {
            fields: {
              cvv: {
                type: 'password',
              },
            },
          },
        },
        threeDSecure: {
          amount,
        },
        locale,
      })
```
- Open 3D-secure modal:
```
await braintreeInstance.requestPaymentMethod()
```
- While 3D-secure modal is open call teardown:
```
braintreeInstance.teardown()
```
#### Actual result
3D-secure modal's markup present in the DOM:

image

#### Expected result
3D-secure modal's markup is not present in the DOM

### Additional notes
It looks like `braintreeInstance.teardown()` is aware of 3D-secure modal and tries to [teardown](https://github.com/braintree/braintree-web-drop-in/blob/master/src/dropin.js#L723) it but [ThreeDSecure.prototype.teardown](https://github.com/braintree/braintree-web-drop-in/blob/master/src/lib/three-d-secure.js#L92) doesn't call [ThreeDSecure.prototype._cleanupModal](https://github.com/braintree/braintree-web-drop-in/blob/master/src/lib/three-d-secure.js#L96).

P.S. I've managed to remove 3D-secure modal's markup by calling `braintreeInstance._threeDSecure.cancel()` before `braintreeInstance.teardown()`, but I believe it shoudn't be necessary

### PR DESCRIPTION
**Pull request by crookedneighbor**
closes #463

### Summary

If teardown is called while 3ds modal is open, the modal doesn't get cleaned up from the DOM.

### Checklist

- [x] Added a changelog entry

### CODE REVIEW

File: test/unit/lib/three-d-secure.js [hunk 1]
```diff
@@ -230,16 +230,25 @@ describe('ThreeDSecure', function () {
...
+    });
 
-      return tds.teardown().then(function () {
+    it('calls teardown on 3ds instance', function () {
+      return this.tds.teardown().then(function () {
         expect(this.threeDSecureInstance.teardown).to.be.calledOnce;
       }.bind(this));
     });
+
+    it('cleanus up modal', function () {
```
Comment (quinnjn) [inline test/unit/lib/three-d-secure.js]: Extra 'u' in 'cleans'
